/**
 * lib/fc/store.ts
 *
 * SERVER-ONLY read layer for FC pages. Reads engine artefacts from disk:
 * betting-machine-fc/{picks.json, matches_detailed.json, tracker_snapshot.json,
 * config.json}. No model logic lives here — filtering/sorting/pagination only
 * mirror the deleted engine's GET handlers so the UI contract stays stable
 * when the engine is restored (brief §11.4.1: one-way data flow).
 *
 * MUST NOT be imported by client components.
 */
import fs from 'node:fs';
import path from 'node:path';
import type {
  FcPick,
  HealthResponse,
  MatchesResponse,
  PicksResponse,
  TrackerResponse,
} from './types';

const FC_DIR = path.join(process.cwd(), 'betting-machine-fc');

function readJson<T>(file: string, fallback: T): T {
  try {
    const raw = fs.readFileSync(path.join(FC_DIR, file), 'utf-8');
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

export function readEngineConfig(): Record<string, unknown> {
  return readJson<Record<string, unknown>>('config.json', {});
}

function formulaVersion(cfg: Record<string, unknown>): string {
  const f = cfg['formula'];
  if (f && typeof f === 'object' && typeof (f as Record<string, unknown>)['version'] === 'string') {
    return (f as Record<string, unknown>)['version'] as string;
  }
  return 'unknown';
}

export function engineOffline(): boolean {
  // Engine scan output was pruned in 6fa01ec; live picks/schedule exist only
  // when picks.json / matches_detailed.json are (re)generated by a scan.
  return !fs.existsSync(path.join(FC_DIR, 'picks.json')) && !fs.existsSync(path.join(FC_DIR, 'matches_detailed.json'));
}

/** Health mirrors engine GET /api/health shape (+ engine_offline flag). */
export function readHealth(): HealthResponse {
  const cfg = readEngineConfig();
  const last = typeof cfg['last_successful_scan_at'] === 'string' ? (cfg['last_successful_scan_at'] as string) : null;
  const offline = engineOffline();
  const diag = (cfg['last_scan_diagnostics'] ?? {}) as Record<string, unknown>;
  return {
    status: offline ? 'offline' : 'healthy',
    service: 'FC Picks (Next.js read layer)',
    timestamp: new Date().toISOString(),
    scan_state: {
      is_running: false,
      last_scan_time: last,
      last_scan_count: Number(cfg['last_successful_scan_count'] ?? 0),
      last_scan_picks: Number(cfg['last_successful_scan_picks'] ?? 0),
      error: offline ? 'Engine scan output missing (engine pruned/offline).' : null,
      progress: '',
      diagnostics: diag,
    },
    formula_version: formulaVersion(cfg),
    engine_offline: offline,
  };
}

export interface PickQuery {
  market?: string;
  league?: string;
  min_odds?: number;
  max_odds?: number;
  min_ev?: number;
  search?: string;
  sort_by?: string;
  sort_order?: string;
  limit?: number;
  offset?: number;
}

const ODDS_FLOOR_ABS = 1.5;

/** Picks mirrors engine GET /api/picks (future-only, filter/sort/paginate). */
export function readPicks(q: PickQuery): PicksResponse {
  const cfg = readEngineConfig();
  const nowSec = Date.now() / 1000;
  const raw = readJson<FcPick[]>('picks.json', []);
  const future = raw.filter((p) => Number(p?.start_ts ?? 0) > nowSec && typeof p?.odds === 'number' && typeof p?.ev === 'number');

  const minOdds = Math.max(q.min_odds ?? 1.5, ODDS_FLOOR_ABS);
  const market = (q.market ?? '').toLowerCase();
  const league = (q.league ?? '').toLowerCase();
  const search = (q.search ?? '').toLowerCase();

  const filtered = future.filter((p) => {
    if (p.odds < minOdds) return false;
    if (q.max_odds !== undefined && p.odds > q.max_odds) return false;
    if (q.min_ev !== undefined && p.ev < q.min_ev) return false;
    if (market && market !== 'all' && (p.market ?? '').toLowerCase() !== market) return false;
    if (league && league !== 'all' && !(p.league ?? '').toLowerCase().includes(league)) return false;
    if (search) {
      const hay = `${p.match ?? ''} ${p.pick ?? ''} ${p.league ?? ''}`.toLowerCase();
      if (!hay.includes(search)) return false;
    }
    return true;
  });

  const reverse = (q.sort_order ?? 'desc').toLowerCase() === 'desc';
  const by = q.sort_by ?? 'rank_score';
  const key = (p: FcPick): number => {
    switch (by) {
      case 'odds': return p.odds ?? 0;
      case 'probability': return p.probability ?? 0;
      case 'start_ts': return p.start_ts ?? 0;
      case 'ev': return p.ev ?? 0;
      case 'rank_score':
      default: return p.rank_score ?? p.ev ?? 0;
    }
  };
  filtered.sort((a, b) => (reverse ? key(b) - key(a) : key(a) - key(b)));

  const limit = Math.min(Math.max(q.limit ?? 50, 1), 500);
  const offset = Math.max(q.offset ?? 0, 0);
  const paged = filtered.slice(offset, offset + limit);

  const leagues = [...new Set(future.map((p) => p.league).filter(Boolean))].sort() as string[];
  const markets = [...new Set(future.map((p) => p.market).filter(Boolean))].sort() as string[];
  const avg = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);

  return {
    summary: {
      total_picks: raw.length,
      qualified_picks: filtered.length,
      top_pick_count: filtered.filter((p) => p.is_top_pick).length,
      official_count: filtered.filter((p) => p.coverage_status === 'full').length,
      watch_count: filtered.filter((p) => p.tier === 'watch').length,
      formula_version: formulaVersion(cfg),
      avg_ev_pct: Math.round(avg(filtered.map((p) => p.ev)) * 10000) / 100,
      avg_odds: Math.round(avg(filtered.map((p) => p.odds)) * 1000) / 1000,
      min_odds_floor: ODDS_FLOOR_ABS,
      selection_limit: Number((cfg['filters'] as Record<string, unknown> | undefined)?.['top_pick_limit'] ?? 50),
      max_picks_per_match: Number((cfg['filters'] as Record<string, unknown> | undefined)?.['top_picks_per_match'] ?? 1),
      leagues,
      markets,
      last_scan_time: typeof cfg['last_successful_scan_at'] === 'string' ? (cfg['last_successful_scan_at'] as string) : null,
    },
    picks: paged,
    pagination: { limit, offset, total: filtered.length },
    engine_offline: engineOffline(),
  };
}

/** Matches mirrors engine GET /api/matches (future-only). */
export function readMatches(limit = 50, offset = 0): MatchesResponse {
  const nowSec = Date.now() / 1000;
  const raw = readJson<Array<Record<string, unknown>>>('matches_detailed.json', []);
  const future = raw.filter((m) => {
    const info = (m['info'] ?? {}) as Record<string, unknown>;
    return Number(info['start_ts'] ?? 0) > nowSec;
  });
  const lim = Math.min(Math.max(limit, 1), 200);
  const off = Math.max(offset, 0);
  return {
    count: future.length,
    matches: future.slice(off, off + lim) as MatchesResponse['matches'],
    pagination: { limit: lim, offset: off, total: future.length },
    engine_offline: engineOffline(),
  };
}

const EMPTY_TRACKER: TrackerResponse = {
  summary: {
    locked_picks: 0, settled_picks: 0, wins: 0, losses: 0, pushes: 0,
    profit_units: 0, roi_pct: 0, hit_rate_pct: 0,
  },
  locked: [], live: [], overdue: [], settled: [],
  status_counts: { locked: 0, live: 0, overdue: 0, settled: 0 },
  market_performance: [],
  by_version: [],
  unit_size: 1.0,
};

/**
 * Tracker is served from tracker_snapshot.json (built by
 * scripts/fc-snapshot.py from bets.db) so the dashboard is a MIRROR, not a
 * second calculator (brief §10.2/§11.4.7). Absent snapshot → honest zeros.
 */
export function readTracker(): TrackerResponse {
  const snap = readJson<TrackerResponse | null>('tracker_snapshot.json', null);
  if (!snap || typeof snap !== 'object' || !snap.summary) {
    return { ...EMPTY_TRACKER, engine_offline: engineOffline() };
  }
  return { ...snap, engine_offline: engineOffline() };
}
